// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMituqSx9axZkEruQICWDxA2S128lt-w',
    appId: '1:489143500380:web:a1dac480cbcc652b31b099',
    messagingSenderId: '489143500380',
    projectId: 'firestore-1ba4c',
    authDomain: 'firestore-1ba4c.firebaseapp.com',
    storageBucket: 'firestore-1ba4c.firebasestorage.app',
    measurementId: 'G-TJ8M0W30K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsthDXxnEe7GZjppz672WsRxv8GO88MI',
    appId: '1:489143500380:android:d4bb630ed0822f4b31b099',
    messagingSenderId: '489143500380',
    projectId: 'firestore-1ba4c',
    storageBucket: 'firestore-1ba4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16IR-G9MH-MUfxVjSLOWtpMxu7P-wcVE',
    appId: '1:489143500380:ios:5094c93cf988f6be31b099',
    messagingSenderId: '489143500380',
    projectId: 'firestore-1ba4c',
    storageBucket: 'firestore-1ba4c.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationUserinfoBlocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB16IR-G9MH-MUfxVjSLOWtpMxu7P-wcVE',
    appId: '1:489143500380:ios:5094c93cf988f6be31b099',
    messagingSenderId: '489143500380',
    projectId: 'firestore-1ba4c',
    storageBucket: 'firestore-1ba4c.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationUserinfoBlocFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMituqSx9axZkEruQICWDxA2S128lt-w',
    appId: '1:489143500380:web:197940591bcd8ba631b099',
    messagingSenderId: '489143500380',
    projectId: 'firestore-1ba4c',
    authDomain: 'firestore-1ba4c.firebaseapp.com',
    storageBucket: 'firestore-1ba4c.firebasestorage.app',
    measurementId: 'G-SHC3F4FTG5',
  );

}